# Default values for prometheus-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: promo/prometheus 
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: prometheus-service
  type: LoadBalancer
  externalPort: 80
  internalPort: 9090

