apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-test-label
    spec:
      containers:
      - name: node-test
        image: gavind/node-test:1
        ports:
        - containerPort: 8080
